### ISSUE TITLE
NPM install doesn't seem to work?

### ISSUE THREAD

**Issue by bxchang04** [ThibaultJanBeyer/dragNdrop#8]
Very simple issue -- I'm assuming running the npm install command ( npm install --save-dev npm-dragndrop) should save me from having to call the script locally in my HTML file ( <script src="js/dnd.min.js"></script> ).

However when I run my repo without the <script src="js/dnd.min.js"></script> nothing works. Is my assumption above incorrect? Pardon me as I don't see the need of installing via NPM (repo works regardless as long as I include the 	<script src="js/dnd.min.js"></script> line).

github: https://github.com/bxchang04/DragNDropTest

Ps: I am not using Bower. I'm assuming NPM is interchangeable with Bower.
Pps: This is the same case when using your other library, dragSelect.

**Comment by ThibaultJanBeyer** [comment]
Hey there @bxchang04 I appreciate that you use multiple of my libraries 🥇 

So `npm` is a package manager, if you run `npm install` it will save the library within a folder called `node_modules` in your project folder (there where you ran the command). Then you could get the library from there, something like `<script src="node_modules/dragselect/dist/ds.min.js></script>`.

Then running `npm install` each time would kinda auto-update the package based on the configuration you have in the `package.json`.
Please check the [npm docs](https://docs.npmjs.com/) to learn more.

Yes, if you use npm you'll probably not need bower and vice-versa.

But if you're new I would suggest to directly link the package like `<script src="https://thibaultjanbeyer.github.io/dragNdrop/dNd.min.js"></script>` so you don't have to deal with package managers at all.

**Comment by bxchang04** [comment]
makes sense, thanks!
